name: flash_cloud
description: 云空间文件管理模块
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  flash_shared:
    path: ../flash_shared
  flash_im_core:
    path: ../flash_im_core
  tolyui_feedback_modal: ^0.0.1
  fx_logger:
    path: ../../packages/fx_logger
  fx_media:
    path: ../../packages/fx_media
  tolyui_mediax_core: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
