# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ws.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ws.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ws.proto\x12\x02im\"9\n\x07WsFrame\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.im.WsFrameType\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x1c\n\x0b\x41uthRequest\x12\r\n\x05token\x18\x01 \x01(\t\".\n\nAuthResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*x\n\x0bWsFrameType\x12\x08\n\x04PING\x10\x00\x12\x08\n\x04PONG\x10\x01\x12\x08\n\x04\x41UTH\x10\x02\x12\x0f\n\x0b\x41UTH_RESULT\x10\x03\x12\x10\n\x0c\x43HAT_MESSAGE\x10\x04\x12\x0f\n\x0bMESSAGE_ACK\x10\x05\x12\x17\n\x13\x43ONVERSATION_UPDATE\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ws_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WSFRAMETYPE']._serialized_start=153
  _globals['_WSFRAMETYPE']._serialized_end=273
  _globals['_WSFRAME']._serialized_start=16
  _globals['_WSFRAME']._serialized_end=73
  _globals['_AUTHREQUEST']._serialized_start=75
  _globals['_AUTHREQUEST']._serialized_end=103
  _globals['_AUTHRESULT']._serialized_start=105
  _globals['_AUTHRESULT']._serialized_end=151
# @@protoc_insertion_point(module_scope)
