# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ws.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/ws.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproto/ws.proto\x12\x02im\"9\n\x07WsFrame\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.im.WsFrameType\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x1c\n\x0b\x41uthRequest\x12\r\n\x05token\x18\x01 \x01(\t\".\n\nAuthResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x8c\x01\n\x19\x46riendRequestNotification\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_user_id\x18\x02 \x01(\t\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\"e\n\x1a\x46riendAcceptedNotification\x12\x11\n\tfriend_id\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\".\n\x19\x46riendRemovedNotification\x12\x11\n\tfriend_id\x18\x01 \x01(\t\"\xb7\x01\n\x1cGroupJoinRequestNotification\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x12\n\ngroup_name\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x10\n\x08nickname\x18\x05 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\x03*\xaa\x02\n\x0bWsFrameType\x12\x08\n\x04PING\x10\x00\x12\x08\n\x04PONG\x10\x01\x12\x08\n\x04\x41UTH\x10\x02\x12\x0f\n\x0b\x41UTH_RESULT\x10\x03\x12\x10\n\x0c\x43HAT_MESSAGE\x10\x04\x12\x0f\n\x0bMESSAGE_ACK\x10\x05\x12\x17\n\x13\x43ONVERSATION_UPDATE\x10\x06\x12\x12\n\x0e\x46RIEND_REQUEST\x10\x07\x12\x13\n\x0f\x46RIEND_ACCEPTED\x10\x08\x12\x12\n\x0e\x46RIEND_REMOVED\x10\t\x12\x16\n\x12GROUP_JOIN_REQUEST\x10\n\x12\x15\n\x11GROUP_INFO_UPDATE\x10\x0b\x12\x0f\n\x0bUSER_ONLINE\x10\x0c\x12\x10\n\x0cUSER_OFFLINE\x10\r\x12\x0f\n\x0bONLINE_LIST\x10\x0e\x12\x10\n\x0cREAD_RECEIPT\x10\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ws_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WSFRAMETYPE']._serialized_start=640
  _globals['_WSFRAMETYPE']._serialized_end=938
  _globals['_WSFRAME']._serialized_start=22
  _globals['_WSFRAME']._serialized_end=79
  _globals['_AUTHREQUEST']._serialized_start=81
  _globals['_AUTHREQUEST']._serialized_end=109
  _globals['_AUTHRESULT']._serialized_start=111
  _globals['_AUTHRESULT']._serialized_end=157
  _globals['_FRIENDREQUESTNOTIFICATION']._serialized_start=160
  _globals['_FRIENDREQUESTNOTIFICATION']._serialized_end=300
  _globals['_FRIENDACCEPTEDNOTIFICATION']._serialized_start=302
  _globals['_FRIENDACCEPTEDNOTIFICATION']._serialized_end=403
  _globals['_FRIENDREMOVEDNOTIFICATION']._serialized_start=405
  _globals['_FRIENDREMOVEDNOTIFICATION']._serialized_end=451
  _globals['_GROUPJOINREQUESTNOTIFICATION']._serialized_start=454
  _globals['_GROUPJOINREQUESTNOTIFICATION']._serialized_end=637
# @@protoc_insertion_point(module_scope)
