# session v0.0.2 - API test chain + doc generator
# Usage: powershell -ExecutionPolicy Bypass -File docs/develop/test_link/session_v0.0.2.ps1

param(
    [string]$Base = "http://127.0.0.1:9600",
    [string]$Phone = "13800001111"
)

$ErrorActionPreference = "Stop"

$docLines = [System.Collections.ArrayList]::new()
function Doc($text) { [void]$docLines.Add($text) }
function Step($n, $desc) { Write-Host ""; Write-Host "========== [$n] $desc ==========" -ForegroundColor Cyan }
function Fail($msg) { Write-Host "[FAIL] $msg" -ForegroundColor Red; exit 1 }
function Pass() { Write-Host "[PASS]" -ForegroundColor Green }

function HttpReq($method, $url, $jsonBody, $tok) {
    $req = [System.Net.HttpWebRequest]::Create($url)
    $req.Method = $method
    $req.ContentType = "application/json; charset=utf-8"
    if ($tok) { $req.Headers.Add("Authorization", "Bearer $tok") }

    if ($jsonBody) {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($jsonBody)
        $req.ContentLength = $bytes.Length
        $stream = $req.GetRequestStream()
        $stream.Write($bytes, 0, $bytes.Length)
        $stream.Close()
    }

    $status = 0
    $respText = ""
    try {
        $resp = $req.GetResponse()
        $status = [int]$resp.StatusCode
        $reader = New-Object System.IO.StreamReader($resp.GetResponseStream(), [System.Text.Encoding]::UTF8)
        $respText = $reader.ReadToEnd()
        $reader.Close()
        $resp.Close()
    } catch [System.Net.WebException] {
        $resp = $_.Exception.Response
        $status = [int]$resp.StatusCode
        if ($resp) {
            $reader = New-Object System.IO.StreamReader($resp.GetResponseStream(), [System.Text.Encoding]::UTF8)
            $respText = $reader.ReadToEnd()
            $reader.Close()
            $resp.Close()
        }
    }
    return @{ Raw = $respText; Status = $status; Obj = $null }
}

function Parse($r) {
    if ($r.Raw) { $r.Raw | ConvertFrom-Json } else { $null }
}

function WriteApi($n, $method, $path, $desc, $paramJson, $respStatus, $respRaw, $tok, $notes) {
    Doc ""; Doc "---"; Doc ""
    Doc "## $n. $method $path"
    Doc ""
    if ($desc) { Doc $desc; Doc "" }
    if ($paramJson) {
        Doc "### Parameters"; Doc ""
        Doc '```json'
        Doc $paramJson
        Doc '```'; Doc ""
    }
    Doc "### Response ``$respStatus``"; Doc ""
    Doc '```json'
    Doc $respRaw
    Doc '```'; Doc ""
    Doc "### curl"; Doc ""
    $curlParts = "curl -s -X $method ""$Base$path"""
    if ($tok) { $curlParts += " ``" + "`n  -H ""Authorization: Bearer <token>""" }
    if ($paramJson) {
        $curlParts += " ``" + "`n  -H ""Content-Type: application/json"" ``"
        $escaped = $paramJson.Replace('"', '\"')
        $curlParts += "`n  -d ""$escaped"""
    }
    Doc '```bash'
    Doc $curlParts
    Doc '```'
    if ($notes) { Doc ""; Doc "> $notes" }
}

Doc "# session v0.0.2 - API Doc"
Doc ""; Doc "Base URL: ``$Base``"; Doc ""
Doc "Auto-generated by test chain."

# === 1. Send SMS ===
Step 1 "POST /auth/sms"
$j1 = "{""phone"":""$Phone""}"
$r = HttpReq "POST" "$Base/auth/sms" $j1
$code = (Parse $r).code
if (-not $code) { Fail "no code: $($r.Raw)" }
Write-Host "code: $code"
Pass
WriteApi 1 "POST" "/auth/sms" "Send SMS verification code." $j1 $r.Status $r.Raw $false

# === 2. Login SMS ===
Step 2 "POST /auth/login - sms"
$j2 = "{""phone"":""$Phone"",""type"":""sms"",""credential"":""$code""}"
$r = HttpReq "POST" "$Base/auth/login" $j2
$obj = Parse $r
$token = $obj.token
if (-not $token) { Fail "login failed: $($r.Raw)" }
Write-Host "user_id: $($obj.user_id), has_password: $($obj.has_password)"
Pass
$j2doc = "{""phone"":""$Phone"",""type"":""sms"",""credential"":""<code>""}"
WriteApi 2 "POST" "/auth/login" "Login with SMS code." $j2doc $r.Status $r.Raw $false

# === 3. Get profile ===
Step 3 "GET /user/profile"
$r = HttpReq "GET" "$Base/user/profile" $null $token
$obj = Parse $r
if (-not $obj.user_id) { Fail "get profile failed" }
Write-Host "nickname: $($obj.nickname), avatar: $($obj.avatar), signature: '$($obj.signature)'"
if ($obj.avatar -notlike "identicon:*") { Fail "avatar should be identicon" }
Pass
WriteApi 3 "GET" "/user/profile" "Get current user profile. Requires Bearer token." $null $r.Status $r.Raw $true

# === 4. Update profile ===
Step 4 "PUT /user/profile"
$j4 = '{"nickname":"TestUser","signature":"hello world"}'
$r = HttpReq "PUT" "$Base/user/profile" $j4 $token
$obj = Parse $r
if ($obj.nickname -ne "TestUser") { Fail "nickname not updated" }
if ($obj.signature -ne "hello world") { Fail "signature not updated" }
Write-Host "nickname: $($obj.nickname), signature: $($obj.signature)"
Pass
WriteApi 4 "PUT" "/user/profile" "Update user profile. All fields optional." $j4 $r.Status $r.Raw $true

# === 5. Change avatar ===
Step 5 "PUT /user/profile - avatar"
$j5 = '{"avatar":"identicon:seed_42"}'
$r = HttpReq "PUT" "$Base/user/profile" $j5 $token
$obj = Parse $r
if ($obj.avatar -ne "identicon:seed_42") { Fail "avatar not updated" }
Write-Host "avatar: $($obj.avatar)"
Pass
WriteApi 5 "PUT" "/user/profile" "Change identicon avatar seed." $j5 $r.Status $r.Raw $true

# === 6. Set password ===
Step 6 "POST /user/password"
$j6 = '{"new_password":"test123456"}'
$r = HttpReq "POST" "$Base/user/password" $j6 $token
Write-Host "status: $($r.Status), body: $($r.Raw)"
Pass
WriteApi 6 "POST" "/user/password" "Set password for the first time." $j6 $r.Status $r.Raw $true

# === 7. Duplicate set - 409 ===
Step 7 "POST /user/password - expect 409"
$j7 = '{"new_password":"another123"}'
$r = HttpReq "POST" "$Base/user/password" $j7 $token
if ($r.Status -ne 409) { Fail "expected 409, got $($r.Status)" }
Write-Host "HTTP $($r.Status) Conflict"
Pass
WriteApi 7 "POST" "/user/password" "Set password again when already set." $j7 $r.Status $(if($r.Raw){"$($r.Raw)"}else{"(empty)"}) $true "Returns 409 if password already exists."

# === 8. Change password ===
Step 8 "PUT /user/password"
$j8 = '{"old_password":"test123456","new_password":"newpass789"}'
$r = HttpReq "PUT" "$Base/user/password" $j8 $token
Write-Host "status: $($r.Status), body: $($r.Raw)"
Pass
WriteApi 8 "PUT" "/user/password" "Change password. Requires old password." $j8 $r.Status $r.Raw $true

# === 9. Wrong old password - 401 ===
Step 9 "PUT /user/password - expect 401"
$j9 = '{"old_password":"wrong","new_password":"whatever123"}'
$r = HttpReq "PUT" "$Base/user/password" $j9 $token
if ($r.Status -ne 401) { Fail "expected 401, got $($r.Status)" }
Write-Host "HTTP $($r.Status) Unauthorized"
Pass
WriteApi 9 "PUT" "/user/password" "Change password with wrong old password." $j9 $r.Status $(if($r.Raw){"$($r.Raw)"}else{"(empty)"}) $true "Returns 401 if old password is incorrect."

# === 10. Login with password ===
Step 10 "POST /auth/login - password"
$j10 = "{""phone"":""$Phone"",""type"":""password"",""credential"":""newpass789""}"
$r = HttpReq "POST" "$Base/auth/login" $j10
$obj = Parse $r
if (-not $obj.token) { Fail "password login failed" }
Write-Host "user_id: $($obj.user_id), has_password: $($obj.has_password)"
Pass
WriteApi 10 "POST" "/auth/login" "Login with password." $j10 $r.Status $r.Raw $false

# === Write doc ===
$docPath = Join-Path $PSScriptRoot "session_v0.0.2_result.md"
$docContent = $docLines -join "`n"
[System.IO.File]::WriteAllText($docPath, $docContent, [System.Text.UTF8Encoding]::new($false))
Write-Host ""
Write-Host "Doc: $docPath" -ForegroundColor Yellow
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  ALL 10 STEPS PASSED" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
