name: flash_im_group
description: Flash IM 群聊模块
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flash_shared:
    path: ../flash_shared
  flash_im_conversation:
    path: ../flash_im_conversation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
