name: fx_updater
description: 通用应用更新框架 - 版本检测 + 策略接口 + 弹窗 UI
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.0
